In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
m1 = [[1.0, 2.0], [3.0, 4.0]]

In [4]:
m2 = np.array(m1)

In [5]:
m3 = tf.constant(m1)

In [6]:
m1

[[1.0, 2.0], [3.0, 4.0]]

In [7]:
m2

array([[1., 2.],
       [3., 4.]])

In [8]:
m3

<tf.Tensor 'Const:0' shape=(2, 2) dtype=float32>

## 리스트, 다차원배열, 텐서 를  텐서로 변환

In [9]:
t1 = tf.convert_to_tensor(m1)

In [10]:
t2 = tf.convert_to_tensor(m2)

In [11]:
t3 = tf.convert_to_tensor(m3)

In [12]:
type(t1)

tensorflow.python.framework.ops.Tensor

In [13]:
type(t2)

tensorflow.python.framework.ops.Tensor

In [14]:
type(t3)

tensorflow.python.framework.ops.Tensor

## 텐서 객체 생성하기

In [15]:
s1 = tf.constant([[1.,2.]])

In [16]:
s1

<tf.Tensor 'Const_3:0' shape=(1, 2) dtype=float32>

In [17]:
s2 = tf.constant([[1],[2]])

In [18]:
s2

<tf.Tensor 'Const_4:0' shape=(2, 1) dtype=int32>

In [19]:
a = np.arange(1,13).

In [20]:
s3 = tf.constant(a)

In [21]:
s3

<tf.Tensor 'Const_5:0' shape=(12,) dtype=int64>

In [22]:
s4 = tf.constant(a.reshape(3,2,2))

In [23]:
s4

<tf.Tensor 'Const_6:0' shape=(3, 2, 2) dtype=int64>

### 내부의 이름 지정

In [24]:
s5 = tf.constant(a.reshape(3,2,2), name="s5")

In [25]:
s5

<tf.Tensor 's5:0' shape=(3, 2, 2) dtype=int64>

## 텐서 정의할 때 다차원 배열은 리스트나 튜플로 shape를 지정할 수 있음

In [26]:
tf.ones([500,500])

<tf.Tensor 'ones:0' shape=(500, 500) dtype=float32>

In [27]:
tf.zeros((500,500))

<tf.Tensor 'zeros:0' shape=(500, 500) dtype=float32>

## 텐서 연산자 생성하기

In [28]:
x = tf.constant([[1,2]])

In [29]:
x

<tf.Tensor 'Const_7:0' shape=(1, 2) dtype=int32>

In [30]:
neg_x = tf.negative(x)

In [31]:
neg_x

<tf.Tensor 'Neg:0' shape=(1, 2) dtype=int32>

## 세션으로 실행하기

- 세션 객체를 만들고 해당 연산을 run 메소드로 실행

In [32]:
with tf.Session() as sess :
    result = sess.run(neg_x)

In [33]:
result

array([[-1, -2]], dtype=int32)

## 대화형 세션 처리하기

- 대화형 세션은 내부의 eval 메소드로 직접 실행

In [34]:
sess = tf.InteractiveSession()

In [35]:
result_ = neg_x.eval()

In [36]:
result

array([[-1, -2]], dtype=int32)

In [37]:
s1.eval()

array([[1., 2.]], dtype=float32)

In [38]:
s2.eval()

array([[1],
       [2]], dtype=int32)

In [39]:
sess.close()

### 세션이 종료 후에는 실행이 안됨

In [40]:
s3.eval()

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

## 디바이스 장비 처리 알아보기

- 로그 정보는 shell 창에 출력됨

In [41]:
with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess :
    result = sess.run(neg_x)

In [42]:
result

array([[-1, -2]], dtype=int32)

## 변수 사용하기

In [43]:
sess = tf.InteractiveSession()

In [44]:
raw_data = [1.,2.,8,-1.,0.,5.5, 6.,13]

In [45]:
spike = tf.Variable(False)

Instructions for updating:
Colocations handled automatically by placer.


In [46]:
spike.initializer.run()

In [47]:
spike.eval()

False

In [49]:
for i in range(1, len(raw_data)) :
    if raw_data[i] - raw_data[i-1] > 5 :
        updater = tf.assign(spike, True)
        updater.eval()
    else :
        tf.assign(spike, False).eval()
    print('spike', spike.eval())
    
sess.close()

spike False
spike True
spike False
spike False
spike True
spike False
spike True
