In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.12.0'

In [6]:
sess = tf.InteractiveSession()

## 전치행렬 알아보기 

In [12]:
A = tf.constant([[1,2,3],[4,5,6]])

In [19]:
tf.transpose(A).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
y = tf.constant([[[ 1,  2,  3],
                      [ 4,  5,  6]],
                     [[ 7,  8,  9],
                      [10, 11, 12]]])

In [22]:
y.get_shape()

TensorShape([Dimension(2), Dimension(2), Dimension(3)])

### 축을 1과 2일 스와핑하기

In [25]:
yt = tf.transpose(y, perm=[0, 2, 1]).eval()

In [27]:
yt.shape

(2, 3, 2)

In [28]:
yt1 = tf.transpose(y, perm=[1, 2, 0]).eval()

In [29]:
yt1.shape

(2, 3, 2)

## 행렬곱 처리

In [30]:
A.get_shape()

TensorShape([Dimension(2), Dimension(3)])

In [31]:
x = tf.constant([1,0,1])

In [32]:
x.get_shape()

TensorShape([Dimension(3)])

In [34]:
try :
    tf.matmul(A,x).eval()
    
except Exception as e :
    print(e)

Shape must be rank 2 but is rank 1 for 'MatMul_4' (op: 'MatMul') with input shapes: [2,3], [3].


### 텐서플로우는 2차원 이상만 행렬곱 처리가능 : 차원을 늘리기 

In [35]:
x1 = tf.expand_dims(x,1)

In [36]:
x1.get_shape()

TensorShape([Dimension(3), Dimension(1)])

In [37]:
tf.matmul(A,x1).eval()

array([[ 4],
       [10]])

## 넘파이는 차원이 달라도 확장해서 계산함

In [38]:
import numpy as np

In [39]:
a = np.array([1,2,3])

In [40]:
Aa = np.random.randint(1,9,(3,3))

In [41]:
np.dot(Aa,a)

array([18, 24, 40])

In [42]:
np.dot(a,Aa)

array([28, 37, 28])