In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.12.0'

In [3]:
sess = tf.InteractiveSession()

## 상수값을 가지고 텐서 생성 

In [4]:
a = tf.constant(100)

In [5]:
a.eval()

100

## 특정값을 모양에 맞춰 처리하기

In [6]:
f = tf.fill((3,3), 1)

In [8]:
f

<tf.Tensor 'Fill:0' shape=(3, 3) dtype=int32>

In [7]:
f.eval()

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
z = tf.zeros((10,10))

In [10]:
z.eval()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [11]:
o = tf.ones((10,10))

In [12]:
o.eval()

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [14]:
zf = tf.zeros_like(f) 

In [15]:
zf.eval()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
of = tf.ones_like(f) 

In [17]:
of.eval()

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## 정규분포

In [18]:
st = tf.random_normal((3,4), 0, 1)

In [19]:
st.eval()

array([[-0.32517073, -0.30580372, -0.27747777, -0.47355172],
       [ 1.303057  , -0.02395595, -0.78182304, -0.971433  ],
       [-0.8186558 ,  0.26065916,  0.12861998, -0.18778741]],
      dtype=float32)

## 절단 정규분포

      평균과 분산,  평균을 기준으로 표준편차보다 크거나 작은 데이터를 제외해서 

In [21]:
ft = tf.truncated_normal((3,4), 0, 1)

In [22]:
ft.eval()

array([[ 0.77500284, -0.03589226,  0.93506175,  0.10749968],
       [-0.5481026 , -0.30997282, -1.3950253 , -0.12765916],
       [ 0.6077578 , -0.663733  , -1.2712312 , -1.6461376 ]],
      dtype=float32)

## 균등분포 

     최소값과 최대값 사이의 균등분포

In [29]:
ut = tf.random_uniform((3,4), 0, 1)

In [30]:
eut = ut.eval()

In [32]:
eut

array([[0.56465137, 0.25671148, 0.8919338 , 0.72988296],
       [0.4845674 , 0.1937306 , 0.5948851 , 0.57585454],
       [0.32801998, 0.46991122, 0.34732878, 0.12536836]], dtype=float32)

## 텐서 내부의 원소를 섞기

In [31]:
tf.random_shuffle(eut).eval()

array([[0.32801998, 0.46991122, 0.34732878, 0.12536836],
       [0.56465137, 0.25671148, 0.8919338 , 0.72988296],
       [0.4845674 , 0.1937306 , 0.5948851 , 0.57585454]], dtype=float32)