In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.13.1'

## 넘파이와 텐서플로우 숫자 자료형은 일치

In [3]:
import numpy as np

In [4]:
np.int32 == tf.int32

True

In [10]:
np.float32 == tf.float32

True

In [11]:
np.complex64 == tf.complex64

True

## 문자열 자료형은 불일치

In [5]:
np.string_ == tf.string

False

In [7]:
np.str == tf.string

False

##  넘파이를 직접 계산에 사용하기 

In [12]:
a = np.array([2,3])

In [13]:
b = np.array([4,5])

In [14]:
a + b

array([6, 8])

In [15]:
c = tf.add(a,b)

In [16]:
sess = tf.Session()

In [17]:
sess.run(c)

array([6, 8])

In [18]:
sess.run(tf.shape(a))

array([2], dtype=int32)

In [19]:
sess.close()