In [1]:
import tensorflow as tf

In [2]:
X = tf.placeholder(tf.float32, [None, 3])

In [3]:
X

<tf.Tensor 'Placeholder:0' shape=(?, 3) dtype=float32>

In [4]:
x_data = [[1,2,3],[4,5,6]]

In [6]:
W = tf.Variable(tf.random_normal([3,2]))

In [7]:
b = tf.Variable(tf.random_normal([2,1]))

In [8]:
expr = tf.matmul(X,W) + b

In [9]:
sess = tf.Session()

In [10]:
sess.run(tf.global_variables_initializer())

In [11]:
x_data

[[1, 2, 3], [4, 5, 6]]

In [12]:
sess.run(W)

array([[ 0.46561685, -0.96077234],
       [ 0.03669956, -0.9461489 ],
       [-0.021984  ,  0.5189663 ]], dtype=float32)

In [13]:
sess.run(b)

array([[-1.9965851 ],
       [-0.57515705]], dtype=float32)

In [15]:
sess.run(expr,  feed_dict={X: x_data})

array([[-1.5235212, -3.292756 ],
       [ 1.3389041, -6.0351925]], dtype=float32)